# ä¸»è¦è®¾ç½®
mainSections = ["posts"]

# ä¾§è¾¹æ è®¾ç½®
[sidebar]
emoji = "ğŸ§ª"
subtitle = "åŒ–å­¦è”åˆåä¼šçš„åšå®¢"

# æœç´¢è®¾ç½®
[sidebar.search]
enable = true

# å°éƒ¨ä»¶è®¾ç½®
[widgets]
enabled = ["search", "archives", "tag-cloud"]  # å¯ç”¨æœç´¢å°éƒ¨ä»¶

# æœç´¢é…ç½®
[search]
enable = true

[search.algolia]
enable = false

[search.fuse]
enable = true
isCaseSensitive = false
minMatchCharLength = 2
shouldSort = true
location = 0
distance = 100
threshold = 0.3
keys = ["title", "permalink", "summary", "content"] 