# ä¸»è¦è®¾ç½®
mainSections = ["posts"]

# ä¾§è¾¹æ è®¾ç½®
[sidebar]
emoji = "ğŸ§ª"
subtitle = "åŒ–å­¦è”åˆåä¼šçš„åšå®¢"
highlight = true

# æœç´¢è®¾ç½®
[sidebar.search]
enable = true

# å°éƒ¨ä»¶è®¾ç½®
[widgets]
enabled = ["search", "archives", "tag-cloud", "categories"]  # å¯ç”¨æœç´¢å°éƒ¨ä»¶

# æœç´¢é…ç½®
[search]
enable = true

[search.algolia]
enable = false

[search.fuse]
enable = true
isCaseSensitive = false
minMatchCharLength = 2
shouldSort = true
location = 0
distance = 100
threshold = 0.3
keys = ["title", "permalink", "summary", "content"]

[sidebar.nav]
enable = true    # å¯ç”¨å¯¼èˆª
expand = true    # å¯ç”¨å±•å¼€/æŠ˜å åŠŸèƒ½

# æ·»åŠ åˆ—è¡¨é¡µé¢é…ç½®
[list]
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
enableSidebar = true    # è¿™ä¸ªå¾ˆé‡è¦ï¼Œç¡®ä¿åˆ—è¡¨é¡µé¢å¯ç”¨ä¾§è¾¹æ 

# æ·»åŠ åˆ†ç±»é¡µé¢é…ç½®
[taxonomy]
showHero = true
enableSidebar = true    # ç¡®ä¿åˆ†ç±»é¡µé¢å¯ç”¨ä¾§è¾¹æ  