# åŸºç¡€é…ç½®
baseURL = 'https://ChemUAsso-CN.github.io/'
languageCode = 'zh-cn'
title = 'åŒ–å­¦è”åˆåä¼š'
copyright = 'ChemUnionAsso-CN'

# ä¸»é¢˜é…ç½®
theme = "hugo-theme-stack"  # æˆ– "kagome"

# è¾“å‡ºé…ç½®
[outputs]
home = ["HTML", "RSS", "JSON"]

# èœå•é…ç½®
[menu]
  [[menu.main]]
    name = "é¦–é¡µ"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "å…³äºæˆ‘ä»¬"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "åšå®¢ä¸æ–‡ç« "
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "è”ç³»æ–¹å¼"
    url = "/contact/"
    weight = 4

# åŸºç¡€å‚æ•°
[params]
mainSections = ["posts"]

[params.article]
showAuthor = true
math = true

[params.sidebar]
emoji = "ğŸ§ª"
subtitle = "åŒ–å­¦è”åˆåä¼šçš„åšå®¢"

[params.footer]
since = 2025
customText = "ChemUnionAsso-CN åŒ–å­¦è”åˆåä¼š"

[markup.goldmark.renderer]
unsafe = true