# åŸºç¡€é…ç½®
baseURL = 'https://ChemUAsso-CN.github.io/'
languageCode = 'zh-cn'
title = 'åŒ–å­¦è”åˆåä¼š'
copyright = 'ChemUnionAsso-CN'

# ä¸»é¢˜é…ç½®
theme = "hugo-theme-stack"  # æˆ– "kagome"

# è¾“å‡ºé…ç½®
[outputs]
home = ["HTML", "RSS", "JSON"]


# åŸºç¡€å‚æ•°
[params]
mainSections = ["posts"]

[params.article]
showAuthor = true
math = true

[params.sidebar]
emoji = "ğŸ§ª"
subtitle = "åŒ–å­¦è”åˆåä¼šçš„åšå®¢"
highlight = true

[params.footer]
since = 2025
customText = "ChemUnionAsso-CN åŒ–å­¦è”åˆåä¼š"

[markup]
  [markup.goldmark.renderer]
    unsafe = true